name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for GH Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Remove old build files
        run: |
          rm -rf dist

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
